version: "3.7"

services:
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"

    networks:
      - backend

  cube:
    container_name: cube
    image: cubejs/cube
    ports:
      - 4000:4000
      - 15432:15432
    env_file: ./packages/cube/.env
    volumes:
      - ./packages/cube:/cube/conf

    networks:
      - backend

  db:
    image: postgres:15.3
    command: [ "postgres", "-c", "log_statement=all" ]
    container_name: db
    ports:
      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: ecosync

    volumes:
      - ./packages/db/tmp/pg/data:/var/lib/postgresql/data

    networks:
      - backend

  web:
    container_name: web
    build:
      dockerfile: Dockerfile.web
    ports:
      - 3000:3000
    networks:
      - backend

networks:
  backend:
