FROM node:20
WORKDIR /app
COPY . .
RUN npm ci
RUN curl -fsSL https://bun.sh/install | bash
RUN curl -fsSL https://bun.sh/install | bash -s "bun-v1.0.0"
RUN npm run reset -w @ecosync/db
RUN npm run build -w @ecosync/web
EXPOSE 3000
CMD npm start -w @ecosync/web